# Navigation

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the first project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893).

### 1. Start the Environment

We begin by importing some necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Banana.app"`
- **Windows** (x86): `"path/to/Banana_Windows_x86/Banana.exe"`
- **Windows** (x86_64): `"path/to/Banana_Windows_x86_64/Banana.exe"`
- **Linux** (x86): `"path/to/Banana_Linux/Banana.x86"`
- **Linux** (x86_64): `"path/to/Banana_Linux/Banana.x86_64"`
- **Linux** (x86, headless): `"path/to/Banana_Linux_NoVis/Banana.x86"`
- **Linux** (x86_64, headless): `"path/to/Banana_Linux_NoVis/Banana.x86_64"`

For instance, if you are using a Mac, then you downloaded `Banana.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Banana.app")
```

In [2]:
env = UnityEnvironment(file_name="./Banana_Linux_NoVis/Banana.x86_64")

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: BananaBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 37
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

The simulation contains a single agent that navigates a large environment.  At each time step, it has four actions at its disposal:
- `0` - walk forward 
- `1` - walk backward
- `2` - turn left
- `3` - turn right

The state space has `37` dimensions and contains the agent's velocity, along with ray-based perception of objects around agent's forward direction.  A reward of `+1` is provided for collecting a yellow banana, and a reward of `-1` is provided for collecting a blue banana. 

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents in the environment
print('Number of agents:', len(env_info.agents))

# number of actions
action_size = brain.vector_action_space_size
print('Number of actions:', action_size)

# examine the state space 
state = env_info.vector_observations[0]
print('States look like:', state)
state_size = len(state)
print('States have length:', state_size)

Number of agents: 1
Number of actions: 4
States look like: [1.         0.         0.         0.         0.84408134 0.
 0.         1.         0.         0.0748472  0.         1.
 0.         0.         0.25755    1.         0.         0.
 0.         0.74177343 0.         1.         0.         0.
 0.25854847 0.         0.         1.         0.         0.09355672
 0.         1.         0.         0.         0.31969345 0.
 0.        ]
States have length: 37


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action (uniformly) at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [5]:
env_info = env.reset(train_mode=False)[brain_name] # reset the environment
state = env_info.vector_observations[0]            # get the current state
score = 0                                          # initialize the score
while True:
    action = np.random.randint(action_size)        # select an action
    env_info = env.step(action)[brain_name]        # send the action to the environment
    next_state = env_info.vector_observations[0]   # get the next state
    reward = env_info.rewards[0]                   # get the reward
    done = env_info.local_done[0]                  # see if episode has finished
    score += reward                                # update the score
    state = next_state                             # roll over the state to next time step
    if done:                                       # exit loop if episode finished
        break
    
print("Score: {}".format(score))

Score: 0.0


When finished, you can close the environment.

In [6]:
# env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [5]:
from dqn_agent import Agent
from collections import deque
agent = Agent(37, 4, 0)

In [ ]:
def dqn(n_episodes=2000, max_t=1000, eps_start=1.0, eps_end=0.01, eps_decay=0.995):
    """Deep Q-Learning.
    
    Params
    ======
        n_episodes (int): maximum number of training episodes
        max_t (int): maximum number of timesteps per episode
        eps_start (float): starting value of epsilon, for epsilon-greedy action selection
        eps_end (float): minimum value of epsilon
        eps_decay (float): multiplicative factor (per episode) for decreasing epsilon
    """
    scores = []                        # list containing scores from each episode
    scores_window = deque(maxlen=100)  # last 100 scores
    eps = eps_start                    # initialize epsilon
    for i_episode in range(1, n_episodes+1):
        env_info = env.reset(train_mode=True)[brain_name]
        state = env_info.vector_observations[0]
        score = 0
        for t in range(max_t):
            action = agent.act(state, eps)
            env_info = env.step(action)[brain_name] 
            next_state = env_info.vector_observations[0]   
            reward = env_info.rewards[0]
            done = env_info.local_done[0]  
            agent.step(state, action, reward, next_state, done)
            state = next_state
            score += reward
            if done:
                break 
        scores_window.append(score)       # save most recent score
        scores.append(score)              # save most recent score
        eps = max(eps_end, eps_decay*eps) # decrease epsilon
        print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)), end="")
        if i_episode % 100 == 0:
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
        if np.mean(scores_window)>=200.0:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i_episode-100, np.mean(scores_window)))
            torch.save(agent.qnetwork_local.state_dict(), 'checkpoint.pth')
            break
    return scores

scores = dqn()

# plot the scores
fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(np.arange(len(scores)), scores)
plt.ylabel('Score')
plt.xlabel('Episode #')
plt.show()

Episode 100	Average Score: 1.00
Episode 200	Average Score: 3.93
Episode 300	Average Score: 7.56
Episode 400	Average Score: 11.26
Episode 477	Average Score: 13.21

In [11]:
states, actions, rewards, next_states, dones = agent.memory.sample()

In [15]:
states

tensor([[  0.0000,   1.0000,   0.0000,  ...,   0.6267,  -0.0000,
         -12.4295],
        [  0.0000,   1.0000,   0.0000,  ...,   0.0041,  -0.0007,
           0.0010],
        [  0.0000,   0.0000,   1.0000,  ...,   0.0039,   0.0000,
           0.0000],
        ...,
        [  0.0000,   1.0000,   0.0000,  ...,   0.0000,   0.0000,
           0.0000],
        [  1.0000,   0.0000,   0.0000,  ...,   0.1910,   0.0000,
          -0.0000],
        [  0.0000,   1.0000,   0.0000,  ...,   0.0048,  -0.0001,
           0.0001]], device='cuda:0')

In [44]:
argmaxes = agent.qnetwork_local(states).detach().argmax(1).unsqueeze(-1)

In [46]:
argmaxes

tensor([[ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 1],
        [ 3],
        [ 3],
        [ 3],
        [ 3]], device='cuda:0')

In [27]:
agent.qnetwork_local(states)

tensor([[ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963

In [40]:
argmaxes.unsqueeze(-1)

tensor([[ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 1],
        [ 3],
        [ 3],
        [ 3],
        [ 3]], device='cuda:0')

In [38]:
torch.arange(agent.qnetwork_local(states).detach().size(0))

tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
         10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,
         20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,
         30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,
         40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,
         50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
         60.,  61.,  62.,  63.])

In [42]:
agent.qnetwork_local(states).detach()

tensor([[ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963,  0.0978],
        [ 0.0962,  0.0976,  0.0963

In [41]:
agent.qnetwork_local(states).detach().gather(1, argmaxes.unsqueeze(-1))

tensor(1.00000e-02 *
       [[ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 9.7787],
        [ 

In [32]:
import torch

In [33]:
torch.index_select(agent.qnetwork_local(states).detach(), 1, argmaxes)

tensor([[ 0.0978,  0.0978,  0.0978,  ...,  0.0978,  0.0978,  0.0978],
        [ 0.0978,  0.0978,  0.0978,  ...,  0.0978,  0.0978,  0.0978],
        [ 0.0978,  0.0978,  0.0978,  ...,  0.0978,  0.0978,  0.0978],
        ...,
        [ 0.0978,  0.0978,  0.0978,  ...,  0.0978,  0.0978,  0.0978],
        [ 0.0978,  0.0978,  0.0978,  ...,  0.0978,  0.0978,  0.0978],
        [ 0.0978,  0.0978,  0.0978,  ...,  0.0978,  0.0978,  0.0978]], device='cuda:0')

In [30]:
agent.qnetwork_local(states).detach().index_select(1, argmaxes.unsqueeze(0))

RuntimeError: invalid argument 2: Input tensor must have same size as output tensor apart from the specified dimension at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:29

In [9]:
agent.save('/home/charles/PycharmProjects/p1_navigation/model_weights')

In [10]:
agent.load('/home/charles/PycharmProjects/p1_navigation/model_weights')

In [16]:
import torch

In [21]:
s = torch.from_numpy(state).float().unsqueeze(0).to(torch.device("cuda:0" if torch.cuda.is_available() else "cpu"))

In [40]:
argmax = agent.qnetwork_local(s).float().argmax(1)[0]

In [27]:
agent.qnetwork_local(s).detach().max(1)[0].unsqueeze(1)

tensor([[ 0.4232]], device='cuda:0')

In [44]:
agent.qnetwork_local(s)[0][argmax].unsqueeze(0).unsqueeze(1)

tensor([[ 0.4232]], device='cuda:0')